
version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: kamiloalca
    ports:
      - "3306:3306"
    networks:
      - postgresnet

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: beaver
    ports:
      - "8080:8978"
    volumes:
      - ./:/opt/cloudbeaver/workspace
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - postgresnet

networks:
  postgresnet:
