apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-appi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: front-end
        image: nginx
        ports:
        - containerPort: 80
      - name: back-end
        image: redis
