
version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=KamiSuper#123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8080:8978"
    volumes:
      - ./:/opt/cloudbeaver/workspace
    depends_on:
      - sqlserver
    restart: unless-stopped

volumes:
  sqlserver_data:
#     networks:
#         - netsql
#
# networks:
#   netsql:
#     external: true

