
version: '3'

services:
  pentaho-server:
    image: pentaho/pentaho-server:8.2
    ports:
      - "8080:8080"
    environment:
      - PENTAHO_JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
      - PENTAHO_HOME=/opt/pentaho/server
    volumes:
      - ./pentaho-data:/opt/pentaho/server/data

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: prueba
      MYSQL_USER: kamilo
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
